import SwiftUI
import Charts
import UIKit

// MARK: - Chart Export Utility
/// Utility for exporting SwiftUI charts as images (PNG/PDF)
class ChartExportUtility {
    
    // MARK: - Export Formats
    enum ExportFormat: String, CaseIterable {
        case png = "PNG"
        case pdf = "PDF"
        
        var fileExtension: String {
            switch self {
            case .png: return "png"
            case .pdf: return "pdf"
            }
        }
        
        var mimeType: String {
            switch self {
            case .png: return "image/png"
            case .pdf: return "application/pdf"
            }
        }
    }
    
    // MARK: - Export Methods
    
    /// Export a SwiftUI view as an image
    static func exportView<Content: View>(
        _ view: Content,
        format: ExportFormat,
        size: CGSize = CGSize(width: 800, height: 600)
    ) -> Data? {
        let hostingController = UIHostingController(rootView: view)
        hostingController.view.frame = CGRect(origin: .zero, size: size)
        hostingController.view.backgroundColor = UIColor.systemBackground
        
        // Force layout
        hostingController.view.layoutIfNeeded()
        
        switch format {
        case .png:
            return exportAsPNG(hostingController.view, size: size)
        case .pdf:
            return exportAsPDF(hostingController.view, size: size)
        }
    }
    
    /// Export a chart view as an image
    static func exportChart<Content: View>(
        _ chartView: Content,
        format: ExportFormat,
        title: String,
        size: CGSize = CGSize(width: 800, height: 600)
    ) -> Data? {
        let exportView = ChartExportWrapper(
            chartView: chartView,
            title: title
        )
        
        return Self.exportView(exportView, format: format, size: size)
    }
    
    // MARK: - Private Methods
    
    private static func exportAsPNG(_ view: UIView, size: CGSize) -> Data? {
        UIGraphicsBeginImageContextWithOptions(size, false, 0.0)
        defer { UIGraphicsEndImageContext() }
        
        guard let context = UIGraphicsGetCurrentContext() else { return nil }
        
        // Set background color
        context.setFillColor(UIColor.systemBackground.cgColor)
        context.fill(CGRect(origin: .zero, size: size))
        
        // Render view
        view.layer.render(in: context)
        
        guard let image = UIGraphicsGetImageFromCurrentImageContext() else { return nil }
        return image.pngData()
    }
    
    private static func exportAsPDF(_ view: UIView, size: CGSize) -> Data? {
        let pdfData = NSMutableData()
        
        UIGraphicsBeginPDFContextToData(pdfData, CGRect(origin: .zero, size: size), nil)
        UIGraphicsBeginPDFPage()
        
        guard let context = UIGraphicsGetCurrentContext() else {
            UIGraphicsEndPDFContext()
            return nil
        }
        
        // Set background color
        context.setFillColor(UIColor.systemBackground.cgColor)
        context.fill(CGRect(origin: .zero, size: size))
        
        // Render view
        view.layer.render(in: context)
        
        UIGraphicsEndPDFContext()
        
        return pdfData as Data
    }
}

// MARK: - Chart Export Wrapper
/// Wrapper view for chart exports with title and styling
struct ChartExportWrapper<Content: View>: View {
    let chartView: Content
    let title: String
    
    var body: some View {
        VStack(spacing: 16) {
            // Title
            Text(title)
                .font(.title2)
                .fontWeight(.bold)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
            
            // Chart
            chartView
            
            // Footer
            HStack {
                Text("Generated by QuickLog")
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                Spacer()
                
                Text(Date(), style: .date)
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            .padding(.horizontal)
        }
        .padding()
        .background(Color(.systemBackground))
    }
}

// MARK: - Chart Export View Modifier
/// View modifier for adding export functionality to charts
struct ChartExportModifier: ViewModifier {
    let chartTitle: String
    let exportFormat: ChartExportUtility.ExportFormat
    @State private var showingExportSheet = false
    @State private var exportData: Data?
    
    func body(content: Content) -> some View {
        content
            .overlay(alignment: .topTrailing) {
                Button {
                    exportChart()
                } label: {
                    Image(systemName: "square.and.arrow.up")
                        .font(.caption)
                        .foregroundColor(.blue)
                        .padding(8)
                        .background(Color(.systemBackground))
                        .clipShape(Circle())
                        .shadow(radius: 2)
                }
                .padding(8)
            }
            .sheet(isPresented: $showingExportSheet) {
                if let exportData = exportData {
                    ShareSheet(activityItems: [exportData])
                }
            }
    }
    
    private func exportChart() {
        // This function is used by the ChartExportModifier
        // The actual export logic is handled in the individual chart components
        // and the ChartsView where the export buttons are implemented
        print("Chart export requested - handled by individual chart components")
    }
}

// MARK: - View Extension
extension View {
    /// Add export functionality to a chart view
    func chartExportable(
        title: String,
        format: ChartExportUtility.ExportFormat = .png
    ) -> some View {
        self.modifier(ChartExportModifier(chartTitle: title, exportFormat: format))
    }
}
